[project]
name = "autodo-suite"
version = "0.1.0"
description = "A unified workspace for Autodo suite of tools."
requires-python = ">=3.13"
dependencies = [
    "autodo-engine",
    "autodo-kit",
]

[tool.uv]
workspace = { members = ["../autodo-engine", "../autodo-kit"] }

[tool.uv.sources]
autodo-engine = { workspace = true }
autodo-kit = { workspace = true }
